#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su ; do
	alias $command="sudo $command"
done; unset command

# autoremove
# alias cleanup="pacman -R --noconfirm $(pacman -Qdtq)"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -v" \
	mv="mv -v" \
	rm="rm -v" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="exa -h --color=auto --group-directories-first" \
	l="exa	-al --color=auto --group-directories-first" \
	ll="exa	-al --color=auto --group-directories-first" \
	lll="exa -al --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	gs="git status" \
	ga="git commit -a" \
	gp="git push" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
# remaps script
	remaps="source $HOME/.config/bin/remaps"

# Joplin appimg
alias joplin="$HOME/.local/bin/joplin/Joplin.AppImage"

# mount sdb1
alias cold="mount /dev/sdb1 $HOME/cold_storage/"
alias ucold="umount -l /dev/sdb1"

# unmute
alias unmute="amixer sset Master unmute"

# racknerd server
alias siteroot="ssh -p 33 root@23.234.228.169"

# play music
alias hood="mpv --shuffle /home/doom/zzz/songs/playlists/The_Hood/"
alias home="mpv --shuffle /home/doom/zzz/songs/playlists/Home/"
alias gully="mpv --shuffle /home/doom/zzz/songs/playlists/Bandana_GAnG/"
alias focus="mpv --shuffle /home/doom/zzz/songs/focus/"

# xclip: always get contents in clipboard
alias xclip="xclip -selection clipboard"

# webserver : racknerd.com
alias rack="ssh root@23.234.228.169"

# fzf

ffc() { du -a $HOME/.config $HOME/.local/bin \
	--exclude '.config/libreoffice' \
	--exclude '.config/BraveSoftware' \
	--exclude '.config/@joplin' \
	--exclude '.config/nvim/plugged' \
	--exclude '.config/JetBrains' \
	--exclude '.config/joplin-desktop' \
	| awk '{print $2}' | fzf | xargs -r $EDITOR ; }

ff() { fzf | xargs -r -I {} $EDITOR {} ; }
