require "shub.options"
require "shub.keymaps"
require "shub.plugins"
require "shub.colorscheme"
require "shub.lsp"
-- require "shub.cmp"
-- require "shub.treesitter"
-- require "shub.telescope"
-- require "shub.autopairs"
